---
# tasks file for web_server

- name: Install Utils
  yum:
    name: 
      - unzip
      - curl
      - mysql
  become: true

- name: Install Apache
  yum:
    name: httpd
  become: true

- name: Install php extensions
  yum: 
    name: 
      - php
      - php-mysql
      - php-gd
      - php-ldap
      - php-odbc
      - php-pear
      - php-xml
      - php-xmlrpc
      - php-mbstring
      - php-snmp
      - php-soap
    state: present
  become: true

- name: Install epel-release
  yum:
    name:
      - epel-release
  become: true

- name: Install myphpadmin
  yum:
    name:
      - phpmyadmin
  become: true   
